# deploy/helm/inferx/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inferx.fullname" . }}
  labels:
    {{- include "inferx.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "inferx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inferx.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: INFERX_PORT
              value: "{{ .Values.service.targetPort }}"
          resources:
            {{- if .Values.gpu.enabled }}
            requests:
              {{- toYaml .Values.resources.requests | nindent 14 }}
              {{- toYaml .Values.gpu.resources | nindent 14 }}
            limits:
              {{- toYaml .Values.resources.limits | nindent 14 }}
              {{- toYaml .Values.gpu.resources | nindent 14 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          startupProbes:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
      {{- if .Values.gpu.enabled }}
      nodeSelector:
        {{- toYaml .Values.gpu.nodeSelector | nindent 8 }}
      {{- else if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
